/*
 * Project: Blink Lite
 * Generated by KiFlow AI - Level 3 Autonomous & Realistic
 * Description: LED no GPIO 4
 */


const int PIN_D1_LED_NET = 4; // Connected to D1 pad 2


void setup() {
  Serial.begin(115200);
  Serial.println("Blink Lite - Firmware Initialized");

  
  
  pinMode(PIN_D1_LED_NET, OUTPUT);
  
  
}

void loop() {
  // Add your logic here
  delay(100);
}